version: '3.7'

configs:
  conf_prometheus:
    file: ./prometheus/prometheus.yml
  conf_alertmanager:
    file: ./alertmanager/alertmanager.yml

networks:
  monitoring:
    driver: overlay
    name: monitoring


services:

    prometheus:
      image: prom/prometheus:latest
      configs:
        - source: conf_prometheus
          target: /etc/prometheus/prometheus.yml
      networks:
        - monitoring
      deploy:  
        replicas: 3

      ports:
        - 9090:9090
      labels:
        - traefik.enable=true
        - traefik.docker.network=monitoring
        - traefik.docker.lbswarm=true
        - traefik.http.routers.prometheus-router-http.entrypoints=web
        - traefik.http.routers.prometheus-router-http.rule=PathPrefix(`/prometheus`)
        - traefik.http.routers.prometheus-router-http.service=prometheus-service-http
        - traefik.http.services.prometheus-service-http.loadbalancer.server.port=9090

    alertmanager:
      image: prom/alertmanager:latest

      configs:
        - source: conf_prometheus
          target: /etc/prometheus/prometheus.yml  
      networks:
        - monitoring

      ports:
        - 9093:9093


    pushgateway:
      image: prom/pushgateway:latest
      networks:
        - monitoring

      ports:
        - 9091:9091


    reverse-proxy:
      image: traefik:latest
      command:
        - --api.insecure=true
        - --api.dashboard=true 
        - --providers.docker=true
        - --providers.docker.swarmMode=true
        - --providers.docker.exposedbydefault=true
        - --providers.docker.network=monitoring
        - --entrypoints.web.address=:80
      ports:
        - "80:80"
      networks:
        - monitoring
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    

 

