# Sample config for Prometheus.

global:
  scrape_interval:     15s
  evaluation_interval: 15s


  external_labels:
      monitor: 'example'


rule_files:
  - "splash.rules"

# himself
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['prometheus:9090']

 # PushGateway
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node'
    static_configs:
      - targets: ['node:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:9999']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8080']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      -  'alertmanager:9093'
